"""Admin Assessment Reports page — overall assessment reports generated by facilitators."""

import reflex as rx
from ai_hybrid_evaluator.components.layout.dashboard_shell import admin_shell
from ai_hybrid_evaluator.state.admin_state import AdminReportsState
from ai_hybrid_evaluator.theme import COLORS, FONT_BODY, FONT_DISPLAY


# ─────────────────────────────────────────────────────────────
# 1. Header Banner
# ─────────────────────────────────────────────────────────────

def reports_header_card() -> rx.Component:
    return rx.box(
        rx.hstack(
            rx.box(
                rx.icon("bar-chart-2", size=22, color="#6366F1"),
                background="#EEF2FF",
                padding="0.65em",
                border_radius="10px",
                display="flex",
                align_items="center",
                justify_content="center",
                flex_shrink="0",
            ),
            rx.vstack(
                rx.text(
                    "Assessment Reports",
                    font_family=FONT_DISPLAY,
                    size="4",
                    weight="bold",
                    color=COLORS["ink"],
                ),
                rx.text(
                    "View overall assessment reports generated by facilitators after completion of assessments.",
                    font_family=FONT_BODY,
                    size="2",
                    color=COLORS["slate"],
                ),
                spacing="0",
                align_items="start",
            ),
            spacing="3",
            align_items="center",
        ),
        background=COLORS["surface"],
        border=f"1px solid {COLORS['line']}",
        border_radius="12px",
        padding="1.2em 1.5em",
        width="100%",
    )


# ─────────────────────────────────────────────────────────────
# 2. Summary Stat Card
# ─────────────────────────────────────────────────────────────

def summary_stat_card(
    label: str,
    value: rx.Var,
    subtext: str,
    icon: str,
    icon_color: str,
    icon_bg: str,
) -> rx.Component:
    return rx.box(
        rx.hstack(
            rx.box(
                rx.icon(icon, size=20, color=icon_color),
                background=icon_bg,
                padding="0.75em",
                border_radius="10px",
                display="flex",
                align_items="center",
                justify_content="center",
                flex_shrink="0",
            ),
            rx.vstack(
                rx.text(label, font_family=FONT_BODY, size="1",
                        color=COLORS["slate"], weight="medium"),
                rx.text(value, font_family=FONT_BODY, size="5",
                        weight="bold", color=COLORS["ink"]),
                rx.text(subtext, font_family=FONT_BODY, size="1",
                        color=COLORS["slate"]),
                spacing="0",
                align_items="start",
            ),
            spacing="3",
            align_items="center",
        ),
        background=COLORS["surface"],
        border=f"1px solid {COLORS['line']}",
        border_radius="12px",
        padding="1em 1.4em",
        flex="1",
    )


# ─────────────────────────────────────────────────────────────
# 3. Report Table Row
# ─────────────────────────────────────────────────────────────

def report_table_row(r: dict) -> rx.Component:
    is_selected = AdminReportsState.selected_report_id == r["report_id"]
    return rx.table.row(
        rx.table.cell(
            rx.text(r["index_num"], font_family=FONT_BODY, size="2",
                    weight="medium", color=COLORS["ink"]),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.text(r["assessment_name"], font_family=FONT_BODY, size="2",
                    weight="bold", color=COLORS["ink"]),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.hstack(
                rx.icon("user", size=14, color=COLORS["slate"]),
                rx.text(r["facilitator_name"], font_family=FONT_BODY,
                        size="2", color=COLORS["ink"]),
                spacing="1",
                align_items="center",
            ),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.text(r["candidate_count"].to_string(), font_family=FONT_BODY,
                    size="2", color=COLORS["ink"]),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.text(
                r["overall_score"].to_string(), "%",
                font_family=FONT_BODY, size="2", weight="bold",
                color="#4338CA",
            ),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.vstack(
                rx.text(r["submitted_date"], font_family=FONT_BODY,
                        size="2", color=COLORS["ink"]),
                rx.text(r["submitted_time"], font_family=FONT_BODY,
                        size="1", color=COLORS["slate"]),
                spacing="0",
                align_items="start",
            ),
            vertical_align="middle",
        ),
        rx.table.cell(
            rx.center(
                rx.button(
                    rx.icon("eye", size=14),
                    "View Report",
                    size="2",
                    variant="soft",
                    color_scheme="indigo",
                    font_family=FONT_BODY,
                    cursor="pointer",
                    on_click=AdminReportsState.open_report(r["report_id"]),
                ),
                width="100%",
            ),
            vertical_align="middle",
            text_align="center",
        ),
        cursor="pointer",
        on_click=AdminReportsState.select_report(r["report_id"]),
        background=rx.cond(is_selected, "#F8FAFF", "transparent"),
        _hover={"background": "#F1F5F9"},
    )




# ─────────────────────────────────────────────────────────────
# 5. Bottom Information Banner
# ─────────────────────────────────────────────────────────────

def reports_info_banner() -> rx.Component:
    return rx.box(
        rx.hstack(
            rx.icon("info", size=18, color="#6366F1", flex_shrink="0"),
            rx.text(
                "These reports are generated by facilitators after completing the assessment. "
                "Each report contains the test-wise and overall performance details for the assessment.",
                font_family=FONT_BODY,
                size="2",
                color="#6366F1",
            ),
            spacing="2",
            align_items="center",
            width="100%",
        ),
        background="#F5F3FF",
        border="1px solid #DDD6FE",
        border_radius="10px",
        padding="0.8em 1.2em",
        width="100%",
    )


# ─────────────────────────────────────────────────────────────
# 6. Report Detail Modal Subcomponents (Exact Facilitator Overall Assessment Report)
# ─────────────────────────────────────────────────────────────

def _report_doc_section_banner(icon_name: str, title: str, sec_id: str) -> rx.Component:
    return rx.box(
        rx.hstack(
            rx.icon(icon_name, size=15, color="#4F46E5"),
            rx.text(title, font_family=FONT_BODY, size="2", weight="bold", color="#1E293B"),
            spacing="2",
            align_items="center",
        ),
        id=sec_id,
        background="#EEF2FF",
        border="1px solid #E0E7FF",
        border_radius="6px",
        padding="0.5em 0.85em",
        width="100%",
        margin_top="1.8em",
        margin_bottom="0.8em",
    )


def _report_candidate_status_pill(status: rx.Var) -> rx.Component:
    return rx.match(
        status,
        ("Passed", rx.box(rx.text("Passed", font_family=FONT_BODY, size="1", weight="bold", color="#03543F"), background="#DEF7EC", border_radius="12px", padding="0.2em 0.8em", display="inline-flex")),
        ("Failed", rx.box(rx.text("Failed", font_family=FONT_BODY, size="1", weight="bold", color="#9B1C1C"), background="#FDE8E8", border_radius="12px", padding="0.2em 0.8em", display="inline-flex")),
        rx.box(rx.text("Pending", font_family=FONT_BODY, size="1", weight="bold", color="#854D0E"), background="#FEF08A", border_radius="12px", padding="0.2em 0.8em", display="inline-flex"),
    )


# ─────────────────────────────────────────────────────────────
# 7. Full Report Detail Modal (Exact Finalized Facilitator Report)
# ─────────────────────────────────────────────────────────────

def report_detail_modal() -> rx.Component:
    return rx.dialog.root(
        rx.dialog.content(
            rx.vstack(
                # Modal Control Toolbar
                rx.hstack(
                    rx.hstack(
                        rx.box(
                            rx.icon("file-bar-chart", size=20, color="white"),
                            background="linear-gradient(135deg, #4F46E5, #7C3AED)",
                            padding="0.55em",
                            border_radius="10px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.vstack(
                            rx.hstack(
                                rx.text(
                                    "Assessment Report",
                                    font_family=FONT_DISPLAY, size="4",
                                    weight="bold", color=COLORS["ink"],
                                ),
                                rx.badge("Completed", color_scheme="green", variant="soft", size="1"),
                                spacing="2",
                                align_items="center",
                            ),
                            rx.text(
                                "Overall report submitted by the Facilitator",
                                font_family=FONT_BODY, size="2",
                                color=COLORS["slate"],
                            ),
                            spacing="0",
                            align_items="start",
                        ),
                        spacing="3",
                        align_items="center",
                    ),
                    rx.spacer(),
                    rx.hstack(
                        rx.button(
                            rx.icon(
                                rx.cond(AdminReportsState.is_full_view, "minimize-2", "maximize-2"),
                                size=14,
                            ),
                            rx.cond(AdminReportsState.is_full_view, "Exit Full View", "Full View"),
                            on_click=AdminReportsState.toggle_full_view,
                            size="2",
                            variant="outline",
                            color_scheme="indigo",
                            font_family=FONT_BODY,
                            cursor="pointer",
                        ),
                        rx.button(
                            rx.icon("printer", size=14),
                            "Print",
                            on_click=rx.call_script("window.print();"),
                            size="2",
                            variant="outline",
                            color="#1E293B",
                            border=f"1px solid {COLORS['line']}",
                            font_family=FONT_BODY,
                            cursor="pointer",
                        ),
                        rx.button(
                            rx.icon("download", size=14),
                            "Export PDF",
                            on_click=AdminReportsState.mock_export_report,
                            size="2",
                            variant="solid",
                            color_scheme="indigo",
                            font_family=FONT_BODY,
                            cursor="pointer",
                        ),
                        rx.dialog.close(
                            rx.button(
                                rx.icon("x", size=14),
                                variant="ghost",
                                size="2",
                                color_scheme="gray",
                                font_family=FONT_BODY,
                                cursor="pointer",
                            ),
                        ),
                        spacing="2",
                        align_items="center",
                    ),
                    width="100%",
                    align_items="center",
                    padding_bottom="1.2em",
                    border_bottom=f"1px solid {COLORS['line']}",
                ),

                # Printable Document Sheet (Exact Facilitator Overall Assessment Report)
                rx.box(
                    rx.vstack(
                        # TVS Document Header
                        rx.hstack(
                            rx.image(
                                src="/tvs_logo.png",
                                height="34px",
                                width="auto",
                                object_fit="contain",
                            ),
                            rx.spacer(),
                            rx.text(
                                "GEN AI HYBRID EVALUATOR",
                                font_family=FONT_BODY,
                                size="3",
                                weight="bold",
                                color="#1E293B",
                                letter_spacing="0.04em",
                            ),
                            rx.spacer(),
                            rx.text(
                                "Assessment Report",
                                font_family=FONT_BODY,
                                size="3",
                                weight="bold",
                                color="#1E293B",
                            ),
                            width="100%",
                            align_items="center",
                        ),
                        rx.box(width="100%", height="1px", background="#E2E8F0", margin_y="1.2em"),

                        # Report Metadata Header
                        rx.hstack(
                            rx.vstack(
                                rx.text(
                                    "Overall Assessment Report",
                                    font_family=FONT_DISPLAY,
                                    size="6",
                                    weight="bold",
                                    color="#0F172A",
                                ),
                                rx.hstack(
                                    rx.text(
                                        AdminReportsState.report_assessment_name,
                                        font_family=FONT_BODY,
                                        size="2",
                                        weight="bold",
                                        color="#334155",
                                    ),
                                    rx.text(
                                        "Assessment",
                                        font_family=FONT_BODY,
                                        size="2",
                                        weight="bold",
                                        color="#334155",
                                    ),
                                    spacing="1",
                                    align_items="center",
                                ),
                                rx.text(
                                    "Assessment Type: Overall Assessment",
                                    font_family=FONT_BODY,
                                    size="2",
                                    color="#64748B",
                                ),
                                spacing="1",
                                align_items="start",
                            ),
                            rx.spacer(),
                            rx.vstack(
                                rx.hstack(
                                    rx.text("Test Date", width="105px", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(":", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(rx.cond(AdminReportsState.report_assessment_date != "", AdminReportsState.report_assessment_date, "All Tests"), font_family=FONT_BODY, size="1", color="#0F172A", weight="medium"),
                                    spacing="1", align_items="center",
                                ),
                                rx.hstack(
                                    rx.text("Generated On", width="105px", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(":", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(AdminReportsState.report_submitted_date, font_family=FONT_BODY, size="1", color="#0F172A", weight="medium"),
                                    spacing="1", align_items="center",
                                ),
                                rx.hstack(
                                    rx.text("Generated By", width="105px", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(":", font_family=FONT_BODY, size="1", color="#64748B"),
                                    rx.text(AdminReportsState.report_facilitator_name, font_family=FONT_BODY, size="1", color="#0F172A", weight="medium"),
                                    spacing="1", align_items="center",
                                ),
                                spacing="1",
                                align_items="start",
                            ),
                            width="100%",
                            align_items="start",
                            margin_bottom="1.2em",
                        ),

                        # ── Section 1: Assessment Summary ──────────────
                        _report_doc_section_banner("file-text", "Assessment Summary", "sec-summary"),
                        rx.box(
                            rx.hstack(
                                # Left column
                                rx.vstack(
                                    rx.hstack(
                                        rx.text("Total Candidates", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text(AdminReportsState.report_candidate_count_str, font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    rx.hstack(
                                        rx.text("Evaluated", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text(AdminReportsState.report_candidate_count_str, font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    rx.hstack(
                                        rx.text("Pending", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text("0", font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    spacing="3",
                                    flex="1",
                                    align_items="stretch",
                                ),
                                # Divider
                                rx.box(width="1px", background="#E2E8F0", margin_x="2em", align_self="stretch"),
                                # Right column
                                rx.vstack(
                                    rx.hstack(
                                        rx.text("Pass Percentage (Set by Facilitator)", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text(AdminReportsState.report_pass_rate_str, font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    rx.hstack(
                                        rx.text("Candidates Passed", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text(AdminReportsState.report_passed_count_str, font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    rx.hstack(
                                        rx.text("Candidates Failed", font_family=FONT_BODY, size="2", color="#475467"),
                                        rx.spacer(),
                                        rx.text(AdminReportsState.report_failed_count_str, font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                        width="100%",
                                    ),
                                    spacing="3",
                                    flex="1",
                                    align_items="stretch",
                                ),
                                width="100%",
                                align_items="start",
                            ),
                            background="#F8FAFC",
                            border="1px solid #E2E8F0",
                            border_radius="6px",
                            padding="1.2em 1.5em",
                            width="100%",
                            margin_bottom="1.2em",
                        ),

                        # ── Section 2: Test-wise Performance ──────────────
                        _report_doc_section_banner("layers", "Test-wise Performance", "sec-testwise"),
                        rx.cond(
                            AdminReportsState.report_test_wise_rows.length() == 0,
                            rx.box(
                                rx.text("No test details recorded for this assessment.", font_family=FONT_BODY, size="2", color=COLORS["slate"]),
                                padding="1em",
                            ),
                            rx.table.root(
                                rx.table.header(
                                    rx.table.row(
                                        rx.table.column_header_cell(rx.text("Test Name", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Test Type", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Test Date", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Weightage", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Evaluated", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Average Score", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Pass %", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Status", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                    ),
                                ),
                                rx.table.body(
                                    rx.foreach(
                                        AdminReportsState.report_test_wise_rows,
                                        lambda row: rx.table.row(
                                            rx.table.cell(rx.text(row["name"], font_family=FONT_BODY, size="2", weight="bold", color="#0F172A")),
                                            rx.table.cell(
                                                rx.badge(
                                                    row["type"],
                                                    color_scheme=rx.cond(row["type"] == "Summative", "purple", "blue"),
                                                    variant="soft",
                                                    size="1",
                                                    border_radius="10px",
                                                )
                                            ),
                                            rx.table.cell(rx.text(row["date"], font_family=FONT_BODY, size="2", color="#475467")),
                                            rx.table.cell(rx.text(row["weightage"], font_family=FONT_BODY, size="2", weight="medium", color="#0F172A")),
                                            rx.table.cell(rx.text(row["evaluated"], font_family=FONT_BODY, size="2", color="#334155")),
                                            rx.table.cell(rx.text(row["avg_score"], font_family=FONT_BODY, size="2", weight="bold", color="#4F46E5")),
                                            rx.table.cell(rx.text(row["pass_pct"], font_family=FONT_BODY, size="2", color="#475467")),
                                            rx.table.cell(
                                                rx.box(
                                                    rx.text("Ready", font_family=FONT_BODY, size="1", weight="bold", color="#03543F"),
                                                    background="#DEF7EC",
                                                    border_radius="12px",
                                                    padding="0.2em 0.8em",
                                                    display="inline-flex",
                                                )
                                            ),
                                        ),
                                    ),
                                ),
                                width="100%",
                                variant="surface",
                                margin_bottom="1.2em",
                            ),
                        ),

                        # ── Section 3: Candidate-wise Overall Performance ──
                        _report_doc_section_banner("users", "Candidate-wise Overall Performance", "sec-candidates"),
                        rx.cond(
                            AdminReportsState.report_candidate_table_rows.length() == 0,
                            rx.box(
                                rx.text("No candidate evaluation records found for this report.", font_family=FONT_BODY, size="2", color=COLORS["slate"]),
                                padding="1em",
                            ),
                            rx.table.root(
                                rx.table.header(
                                    rx.table.row(
                                        rx.table.column_header_cell(rx.text("Candidate", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Scores Across Tests", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Overall Score", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                        rx.table.column_header_cell(rx.text("Status", font_family=FONT_BODY, size="2", weight="bold", color="#64748B")),
                                    ),
                                ),
                                rx.table.body(
                                    rx.foreach(
                                        AdminReportsState.report_candidate_table_rows,
                                        lambda row: rx.table.row(
                                            rx.table.cell(
                                                rx.vstack(
                                                    rx.text(row["cand_name"], font_family=FONT_BODY, size="2", weight="bold", color="#0F172A"),
                                                    rx.text(row["cand_id"], font_family=FONT_BODY, size="1", color="#64748B"),
                                                    spacing="0",
                                                    align_items="start",
                                                )
                                            ),
                                            rx.table.cell(
                                                rx.badge(
                                                    row["scores_summary"],
                                                    color_scheme="gray",
                                                    variant="surface",
                                                    size="1",
                                                    border_radius="6px",
                                                    padding="0.25em 0.6em",
                                                )
                                            ),
                                            rx.table.cell(
                                                rx.text(
                                                    row["overall_score"],
                                                    font_family=FONT_BODY,
                                                    size="2",
                                                    weight="bold",
                                                    color="#4F46E5",
                                                )
                                            ),
                                            rx.table.cell(_report_candidate_status_pill(row["status"])),
                                        ),
                                    ),
                                ),
                                width="100%",
                                variant="surface",
                                margin_bottom="1.2em",
                            ),
                        ),

                        # ── Section 4: Pass / Fail Summary ─────────────
                        _report_doc_section_banner("circle-check", "Pass/Fail Summary", "sec-passfail"),
                        rx.box(
                            rx.hstack(
                                rx.vstack(
                                    rx.text("Passed", font_family=FONT_BODY, size="2", color="#059669", weight="medium"),
                                    rx.text(AdminReportsState.report_passed_count_str, font_family=FONT_DISPLAY, size="7", weight="bold", color="#059669"),
                                    rx.text("candidates", font_family=FONT_BODY, size="1", color="#64748B"),
                                    spacing="1", align_items="center",
                                ),
                                rx.vstack(
                                    rx.text("Failed", font_family=FONT_BODY, size="2", color="#DC2626", weight="medium"),
                                    rx.text(AdminReportsState.report_failed_count_str, font_family=FONT_DISPLAY, size="7", weight="bold", color="#DC2626"),
                                    rx.text("candidates", font_family=FONT_BODY, size="1", color="#64748B"),
                                    spacing="1", align_items="center",
                                ),
                                rx.vstack(
                                    rx.text("Pending", font_family=FONT_BODY, size="2", color="#D97706", weight="medium"),
                                    rx.text(AdminReportsState.report_pending_count_str, font_family=FONT_DISPLAY, size="7", weight="bold", color="#D97706"),
                                    rx.text("candidates", font_family=FONT_BODY, size="1", color="#64748B"),
                                    spacing="1", align_items="center",
                                ),
                                spacing="8",
                                justify="center",
                                width="100%",
                            ),
                            background="#F8FAFC",
                            border="1px solid #E2E8F0",
                            border_radius="6px",
                            padding="1.5em",
                            width="100%",
                            margin_bottom="1.2em",
                        ),


                        spacing="0",
                        width="100%",
                        align_items="stretch",
                    ),
                    background="white",
                    border="1px solid #E2E8F0",
                    border_radius="12px",
                    box_shadow="0 1px 3px rgba(0,0,0,0.05)",
                    padding="2.5em 3em",
                    width="100%",
                    id="report-printable-doc",
                ),

                spacing="4",
                width="100%",
                align_items="stretch",
            ),
            style={
                "maxWidth": rx.cond(AdminReportsState.is_full_view, "100vw", "1020px"),
                "width": rx.cond(AdminReportsState.is_full_view, "100vw", "95vw"),
                "maxHeight": rx.cond(AdminReportsState.is_full_view, "100vh", "92vh"),
                "height": rx.cond(AdminReportsState.is_full_view, "100vh", "auto"),
                "borderRadius": rx.cond(AdminReportsState.is_full_view, "0px", "16px"),
                "padding": rx.cond(AdminReportsState.is_full_view, "2em 3em", "1.5em"),
                "overflowY": "auto",
            },
        ),
        open=AdminReportsState.show_report_detail,
        on_open_change=AdminReportsState.set_show_report_detail,
    )


# ─────────────────────────────────────────────────────────────
# 8. Main Reports Page
# ─────────────────────────────────────────────────────────────

def reports_page() -> rx.Component:
    # Left table section
    table_card = rx.box(
        rx.vstack(
            # Top Search and Showing count
            rx.hstack(
                rx.input(
                    rx.input.slot(rx.icon("search", size=15, color=COLORS["placeholder"])),
                    placeholder="Search by assessment name or facilitator...",
                    value=AdminReportsState.search_query,
                    on_change=AdminReportsState.set_search_query,
                    size="2",
                    width="320px",
                    border_radius="8px",
                ),
                rx.spacer(),
                rx.text(
                    AdminReportsState.showing_text,
                    font_family=FONT_BODY,
                    size="2",
                    color=COLORS["slate"],
                ),
                width="100%",
                align_items="center",
                padding_bottom="1em",
            ),

            # Report Table
            rx.cond(
                AdminReportsState.filtered_reports.length() == 0,
                rx.box(
                    rx.vstack(
                        rx.icon("file-text", size=28, color=COLORS["slate"]),
                        rx.text(
                            "No reports found matching your search.",
                            font_family=FONT_BODY,
                            size="2",
                            color=COLORS["slate"],
                            text_align="center",
                        ),
                        align_items="center",
                        spacing="2",
                    ),
                    padding="3em",
                    display="flex",
                    justify_content="center",
                    width="100%",
                ),
                rx.table.root(
                    rx.table.header(
                        rx.table.row(
                            rx.table.column_header_cell(
                                rx.text("#", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                                width="40px",
                            ),
                            rx.table.column_header_cell(
                                rx.text("Assessment", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                            ),
                            rx.table.column_header_cell(
                                rx.text("Facilitator", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                            ),
                            rx.table.column_header_cell(
                                rx.text("Candidates", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                            ),
                            rx.table.column_header_cell(
                                rx.text("Avg. Overall Score", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                            ),
                            rx.table.column_header_cell(
                                rx.text("Report Date", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                            ),
                            rx.table.column_header_cell(
                                rx.center(
                                    rx.text("Action", font_family=FONT_BODY, size="2", weight="bold", color=COLORS["ink"]),
                                    width="100%",
                                ),
                                width="140px",
                                text_align="center",
                            ),
                        ),
                    ),
                    rx.table.body(
                        rx.foreach(
                            AdminReportsState.filtered_reports,
                            lambda r: report_table_row(r),
                        ),
                    ),
                    width="100%",
                ),
            ),

            # Pagination row
            rx.hstack(
                rx.button(
                    rx.icon("chevron-left", size=14),
                    size="1",
                    variant="outline",
                    color_scheme="gray",
                    cursor="default",
                ),
                rx.button(
                    "1",
                    size="1",
                    variant="solid",
                    color_scheme="indigo",
                ),
                rx.button(
                    rx.icon("chevron-right", size=14),
                    size="1",
                    variant="outline",
                    color_scheme="gray",
                    cursor="default",
                ),
                spacing="2",
                justify="center",
                width="100%",
                padding_top="1em",
            ),

            spacing="0",
            width="100%",
        ),
        background=COLORS["surface"],
        border=f"1px solid {COLORS['line']}",
        border_radius="12px",
        padding="1.2em",
        width="100%",
    )

    content = rx.vstack(
        # Top Header Card
        reports_header_card(),

        # Summary stat cards (4 across)
        rx.hstack(
            summary_stat_card(
                "Total Reports",
                AdminReportsState.total_reports_count,
                "Total assessment reports",
                "file-text",
                "#7C3AED",
                "#F5F3FF",
            ),
            summary_stat_card(
                "Total Candidates",
                AdminReportsState.total_candidates_count,
                "Across all reports",
                "users",
                "#10B981",
                "#ECFDF5",
            ),
            summary_stat_card(
                "Average Score",
                AdminReportsState.average_score_str,
                "Across all reports",
                "bar-chart-2",
                "#3B82F6",
                "#EFF6FF",
            ),
            summary_stat_card(
                "Latest Report",
                AdminReportsState.latest_report_date,
                "Most recent submission",
                "calendar",
                "#8B5CF6",
                "#F5F3FF",
            ),
            spacing="4",
            width="100%",
            flex_wrap="wrap",
        ),

        # Main section: Table
        table_card,

        # Bottom informational banner
        reports_info_banner(),

        # Report detail modal (Full View)
        report_detail_modal(),

        spacing="4",
        width="100%",
        align_items="stretch",
    )

    return admin_shell(
        active="reports",
        title="Assessment Reports",
        subtitle="View overall assessment reports generated by facilitators after completion of assessments.",
        content=content,
    )